# Generated by Django 2.1.5 on 2020-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(blank=True, max_length=3, null=True)),
                ('user_code', models.CharField(blank=True, max_length=10, null=True)),
                ('news', models.TextField(blank=True, max_length=255, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image Link')),
            ],
            options={
                'ordering': ('addDate',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fatherName', models.CharField(blank=True, max_length=255, null=True)),
                ('clas', models.CharField(blank=True, choices=[('PREP', 'PREP'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=30, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('houseName', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileNum', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNum', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('video_link', models.URLField(max_length=1000, verbose_name='Video Link')),
                ('description', models.CharField(max_length=500)),
                ('thumbnail_link', models.URLField(max_length=1000, verbose_name='Image Link')),
                ('played_time', models.TimeField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
