# Generated by Django 2.1.5 on 2020-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='class_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
