# Generated by Django 2.1.5 on 2020-07-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Enable',
            field=models.BooleanField(default=True),
        ),
    ]
