# Generated by Django 2.1.5 on 2020-07-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0009_auto_20200709_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='school_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
