# Generated by Django 2.1.5 on 2020-07-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0012_auto_20200716_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='MCQPost_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherStu.MCQ_Post'),
        ),
    ]
