# Generated by Django 2.1.5 on 2020-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0017_auto_20200721_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='modifyDate',
            new_name='modify_at',
        ),
        migrations.AlterField(
            model_name='news',
            name='class_code',
            field=models.CharField(choices=[('PREP', 'PREP'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='school_code',
            field=models.CharField(max_length=3),
        ),
    ]
