# Generated by Django 2.1.5 on 2020-07-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0018_auto_20200722_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='class_code',
            field=models.CharField(choices=[('ALL', 'ALL'), ('PREP', 'PREP'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='news',
            name='school_code',
            field=models.CharField(choices=[('ALL', 'ALL'), ('KAS', 'KAS'), ('DEO', 'DEO'), ('AND', 'AND'), ('GKP', 'GKP')], max_length=3),
        ),
        migrations.AlterField(
            model_name='news',
            name='user_code',
            field=models.CharField(choices=[('ALL', 'ALL'), ('CLASS', 'CLASS'), ('STUDENT', 'STUDENT')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
