# Generated by Django 2.1.5 on 2020-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0019_auto_20200723_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='user_code',
            field=models.CharField(max_length=100),
        ),
    ]
