# Generated by Django 2.1.5 on 2020-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0020_auto_20200723_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='user_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
