# Generated by Django 2.1.5 on 2020-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0021_auto_20200723_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='class_code',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('PREP', 'PREP'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=30, null=True),
        ),
    ]
