# Generated by Django 2.1.5 on 2020-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0023_auto_20200723_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_answer',
            name='que_Image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='que_Image',
            field=models.ImageField(default='Blank', max_length=1000, upload_to='images/'),
        ),
    ]
