# Generated by Django 2.1.5 on 2020-07-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0024_auto_20200724_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
