# Generated by Django 2.1.5 on 2020-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
